first_tdd/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from lists import views as lists_views
from lists import urls as lists_urls

urlpatterns = [
    path('', lists_views.home_page),
    path('admin/', admin.site.urls),
    path('lists/', include(lists_urls)),
]

lists/urls.py
# from django.contrib import admin
from django.urls import path

from lists import views

urlpatterns = [
    path('new/', views.new_list, name='new_list'),
    path('<int:list_id>/', views.view_list, name='view_list'),
]

lists/models.py
from django.db import models
from django.urls import reverse


class Lists(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Items(models.Model):
    text = models.TextField(blank=False)
    list = models.ForeignKey(Lists, on_delete="CASCADE")

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError

from .models import Items, Lists


def home_page(request):
    return render(request, 'home.html')


def view_list(request, list_id):
    list_ = Lists.objects.get(id=list_id)
    error = None
    if request.POST:
        try:
            item = Items(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect(list_)
        except ValidationError:
            error = "You can't have an empty list!"
    context = {
        "list": list_,
        "error": error}
    return render(request, 'list.html', context)


def new_list(request):
    list_ = Lists.objects.create()
    data = request.POST.get("item_text", "")
    item = Items(text=data, list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list!"
        return render(request, 'home.html', {'error': error})
    return redirect(list_)

lists/templates/base.html
<html lang="en">
<head>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To Do List</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">
                    <h1>{%block header_text%}{%endblock%}</h1>
                <form method="POST" action="{%block form_action %}{%endblock%}">
                    <input name="item_text" id="input_text" placeholder="Enter a to-do item" class="form-control input-lg" />
                    {% csrf_token %}
                    {%if error%}
                        <div class="has-error form-group">
                            <span class="help-block">{{error}}</span>
                        </div>
                    {%endif%}

                </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {%block table%}
                {%endblock%}
            </div>
        </div>
    </div>


</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{%url 'new_list'%}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{%block header_text%} A new To-Do List{%endblock%}

{% block form_action %}
    {% url 'view_list' list.id%}
{% endblock %}
{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.items_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}